---
title: modeling
author: <a href = "https://lovetoken.github.io">lovetoken</a>
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_height: 6
    theme: yeti
    toc: yes
    toc_depth: 3
    toc_float: yes
    keep_md: no
---

```{r env_ready, echo = F, warning = F, message = F}
pacman::p_load(knitr, tidyverse, tidyr, ggplot2, data.table, caret, magrittr, lubridate, MLmetrics, gencve)
opts_chunk$set(fig.path = "output/figure/", fig.align = "center", out.width = "90%", warning = F, message = F)

data_path = "data/"
```

<br><br>

## Data ready

### Rawdata read

```{r Rawdata_read}
d <- paste0(data_path, "train.csv") %>% read_csv
```

### Preprocessing & Partition

```{r Preprocessing_&_Partition}
pre_d <- d %>% 
  mutate(month = month(date),
         wday = wday(date, label = T)) %>% 
  mutate_at(vars(store, item, month, wday), as.factor) %>% 
  select(-date)

index <- createDataPartition(pre_d$sales, p = .7, list = F)
train <- pre_d %>% extract(index, )
test <- pre_d %>% extract(-index, )
```

<br><br>

## Modeling

```{r Modeling}
fitControl <- trainControl(method = "repeatedcv", number = 5, repeats = 2, allowParallel = TRUE)
mlMethods <- c("rpart", "pcr", "xgbLinear", "gbm")
models <- mlMethods %>% 
  lapply(function(x) train(sales ~ ., data = train, method = x, trControl = fitControl))
```

<br><br>

## Evaluate

```{r evaluate_function_setting}
evaluate <- function(model, testset, class, ylim = c(1, testset %>% pull(class) %>% max)){
  stopifnot(is.character(class))

  pd <- data.frame(real = pull(testset, class), 
                   pred = predict(model, newdata = testset) %>% unlist) %>% tbl_df %>% 
    arrange(real) %>% 
    mutate(index = 1:nrow(.)) %>% 
    gather(class, value, -index)
    
  p <- ggplot(pd, aes(x = index, y = value, color = class)) + 
    geom_line(size = .3, alpha = .7) + 
    ggtitle(model$modelInfo$label, 
            paste0("process time : ", model$times$everything, " / ", 
                   "SMAPE : ", smape(pull(testset, class), predict(model, newdata = testset) %>% unlist)))
  p
}
```

```{r Evaluate}
models %>% 
  lapply(evaluate, test, "sales")

bestModel <- models %>% 
  lapply(function(x) smape(pull(test, sales), predict(x, newdata = test) %>% unlist)) %>% 
  unlist %>% 
  order %>% extract(1) %>% 
  extract2(models, .)
```

<br><br>

## Full training on selected best model machine learning algorithm

```{r}
selectedMethod <- bestModel$method
bestModel <- train(sales ~ ., data = pre_d, method = selectedMethod, trControl = fitControl)
```

<br><br>

## Predict on real testset

```{r Predict_on_real_testset}
realTest <- paste0(data_path, "test.csv") %>% read_csv 
predY <- realTest %>% 
  mutate(month = month(date),
         wday = wday(date, label = T)) %>% 
  mutate_at(vars(store, item, month, wday), as.factor) %>% 
  select(-date) %>% 
  predict(bestModel, newdata = .)
```

### Output submission

```{r Output_submission}
submissionSet <- paste0(data_path, "sample_submission.csv") %>% 
  fread %>% 
  mutate(sales = predY)

write_csv(submissionSet, "output/submission.csv")
```